var renderpages = 
{
	login:function(req,res)
	{
		
		res.render('website/login.ejs');
	},
	signup:function(req,res)
	{
		res.render('website/signup.ejs');
	},
	forgetpassword:function(req,res)
	{
		if(!req.session.mysess)
		{
		 res.render('website/forgetpassword.ejs');
		}	
	
	},
	otp:function(req,res)
	{
		if(!req.session.mysess)
		{
		res.render('website/otp.ejs');
		}	
		else
		{
			res.redirect('/website/login');
		}
	},
	otp_signup:function(req,res)
	{

		res.render('website/otp_signup.ejs');
	},
	resetpassword:function(req,res)
	{
		if(req.session.mysess)
		{
		res.render('website/resetpassword.ejs');
		}	
	
	},
	resetpassword_signup:function(req,res)
	{
		res.render('website/resetpassword_signup.ejs');
	},
	freeparking:function(req,res)
	{
		if(req.session.mysess)
		{
		 res.render('website/freeparking.ejs');
		}	
		else
		{
		res.redirect('/website/login');
		}
	},
		index:function(req,res)
    {
      if(req.session.mysess)
      {
        res.render('website/index1.ejs');
      }  
      else
      {
        res.render('website/index.ejs');
      }
    },
	paymentsuccessful:function(req,res)
	{
		if(req.session.mysess)
		{
		 res.render('website/paymentsuccessful.ejs');
		}	
		else
		{
			res.redirect('/website/login');
		}
	},
	rentspace:function(req,res)
	{
		if(req.session.mysess)
		{
		res.render('website/rentspace.ejs');
		}	
		else
		{
			res.redirect('/website/login');
		}
	},
	spacebooking:function(req,res)
	{
		if(req.session.mysess)
		{
		 res.render('website/spacebooking.ejs');
		}	
		else
		{
			res.redirect('/website/login');
		}
	},
	spacedetails:function(req,res)
	{
		if(req.session.mysess)
		{
		 res.render('website/spacedetails.ejs');
		 }	
		else
		{
			res.redirect('/website/login');
		}
	},
	  searchresult:function(req,res)
    {
      if(req.session.mysess)
      {
        res.render('website/searchresult.ejs');
      }  
      else
      {
        res.render('website/searchresult1.ejs');
      }
    },	
	underconstruction:function(req,res)
	{
		if(req.session.mysess)
		{
		res.render('website/underconstruction.ejs');
		}	
		else
		{
			res.redirect('/website/login');
		}
	},
	bookingdetails:function(req,res)
	{
		if(req.session.mysess)
		{
		 res.render('website/bookingdetails.ejs');
		}	
		else
		{
			res.redirect('/website/login');
		}

	},
	bookingdetails_past:function(req,res)
	{
		if(req.session.mysess)
		{
		 res.render('website/bookingdetails_past.ejs');
		}	
		else
		{
			res.redirect('/website/login');
		}

	}
	,
	receivedbookings:function(req,res)
	{
		if(req.session.mysess)
		{
		res.render('website/receivedbookings.ejs');
		}	
		else
		{
			res.redirect('/website/login');
		}

	},
	mybooking:function(req,res)
	{
		res.render('website/mybooking.ejs');
	},
	myspacedetails:function(req,res)
	{
		res.render('website/myspacedetails.ejs');

	},
	myspacelist:function(req,res)
	{
		res.render('website/myspacelist.ejs');
	},
	profile:function(req,res)
	{
		if(req.session.mysess)
		{
			res.render('website/profile.ejs');
		}
		
	},
	receivedbookingdetails:function(req,res)
	{
		res.render('website/receivedbookingdetails.ejs');
	},
	payment:function(req,res)
	{
		res.render('website/payment.ejs');
	},
	extend_booking_payment:function(req,res)
	{
		res.render('website/extend_booking_payment.ejs');
	},
	rentspace_payment:function(req,res)
	{
		res.render('website/rentspacePayment.ejs');
	},
	payment_with_card:function(req,res)
	{
		res.render('website/paymentWithCard.ejs');
	}

}
module.exports = renderpages;
